[build]
  publish = "."
  functions = "netlify/functions"

# CORS básico (podés ajustar después)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, x-api-key"
    Access-Control-Allow-Methods = "POST, OPTIONS"